[package]
name = "moonkey"
description = 'Moonbeam Key Tool'
version = "0.1.0"
authors = ["PureStake"]
edition = "2018"
license = 'GPL-3.0-only'
homepage = 'https://moonbeam.network'

[[bin]]
name = "moonkey"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.2"
tiny-bip39 = { version = "0.6" }
libsecp256k1 = { version = "0.3.2" }
primitive-types = "0.9.0"
sha3 = "0.8"
tiny-hderive = "0.3.0"