[workspace]
members = [
    'runtime/moonbeam',
    'runtime/moonriver',
    'runtime/moonshadow',
    'runtime/moonbase',
    'node',
    'node/cli',
    'node/service',
]

[profile.release]
panic = 'unwind'
