[package]
name = "spfkey"
authors = [ "Super Platform Functionality Dev Team" ]
description = "SPF Key Tool"
edition = "2021"
homepage = "https://superpf.io"
license = "GPL-3.0-only"
version = "0.1.1"

[[bin]]
name = "spfkey"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1", features = [ "derive" ] }
cli-opt = { package = "moonbeam-cli-opt", path = "../../../node/cli-opt", default-features = false }
