[package]
name = 'moonbeam'
description = 'Moonbeam Collator'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
version = '0.8.0-dev'
authors = ["PureStake"]
edition = '2018'

[[bin]]
name = 'moonbeam'
path = 'src/main.rs'

[dependencies]
futures = { version = "0.3.1", features = ["compat"] }
moonbeam-cli = { path = "cli" }
moonbeam-service = { path = "service" }

[features]
default = []

test-spec = []

runtime-benchmarks = [
	"moonbeam-cli/runtime-benchmarks",
]
