[package]
authors = ['PureStake']
description = 'Moonbeam Core'
edition = '2018'
homepage = 'https://moonbeam.network'
license = 'Unlicense'
name = 'mb-evm'
repository = 'https://github.com/PureStake/moonbeam/'
version = '0.1.0'


[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
safe-mix = { default-features = false, version = '1.0.0' }
serde = { version = "1.0.102", features = ["derive"] }

# primitives
sp-core = { git = 'https://github.com/paritytech/substrate.git', version = '2.0.0-alpha.7', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate.git', version = '2.0.0-alpha.7', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', version = '2.0.0-alpha.7', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate.git', version = '2.0.0-alpha.7', default-features = false }
sp-staking = { git = 'https://github.com/paritytech/substrate.git', version = '2.0.0-alpha.7', default-features = false }

# frame dependencies
frame-support = { git = 'https://github.com/paritytech/substrate.git', version = '2.0.0-alpha.7', default-features = false }
system = { package = 'frame-system', git = 'https://github.com/paritytech/substrate.git', version = '2.0.0-alpha.7', default-features = false }
pallet-balances = { git = 'https://github.com/paritytech/substrate.git', version = '2.0.0-alpha.7', default-features = false }
pallet-staking = { git = 'https://github.com/paritytech/substrate.git', version = '2.0.0-alpha.7', default-features = false }

[features]
default = ['std']
std = [
	"sp-std/std",
	"sp-staking/std",
    'codec/std',
    'frame-support/std',
    'safe-mix/std',
    'system/std',
	'pallet-staking/std',
]
