[package]
name = "moonbeam-cli"
version = "0.9.0"
authors = ["PureStake"]
edition = "2018"

[dependencies]
log = "0.4.8"
structopt = "0.3.8"
parity-scale-codec = '2.0.0'

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
try-runtime-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }

cumulus-client-cli = { git = "https://github.com/purestake/cumulus", branch = "nimbus-v0.9.6-without-compact-proof" }
cumulus-client-service = { git = "https://github.com/purestake/cumulus", branch = "nimbus-v0.9.6-without-compact-proof" }
cumulus-primitives-core = { git = "https://github.com/purestake/cumulus", branch = "nimbus-v0.9.6-without-compact-proof" }
nimbus-primitives = { git = "https://github.com/purestake/cumulus", branch = "nimbus-v0.9.6-without-compact-proof" }

polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.6" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.6" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.6" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.6" }

service = { package = "moonbeam-service", path = "../service", default-features = false }
cli-opt = { package = "moonbeam-cli-opt", path = "../cli-opt", default-features = false }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }

[features]
default = ["wasmtime"]
wasmtime = ["sc-cli/wasmtime"]
runtime-benchmarks = ["service/runtime-benchmarks"]
