[package]
name = "moonbeam-cli"
version = "0.8.0"
authors = ["PureStake"]
edition = "2018"

[dependencies]
log = "0.4.8"
structopt = "0.3.8"
parity-scale-codec = '2.0.0'

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }
try-runtime-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }

cumulus-client-cli = { git = "https://github.com/purestake/cumulus", branch = "nimbus" }
cumulus-client-service = { git = "https://github.com/purestake/cumulus", branch = "nimbus" }
cumulus-primitives-core = { git = "https://github.com/purestake/cumulus", branch = "nimbus" }
nimbus-primitives = { git = "https://github.com/purestake/cumulus", branch = "nimbus" }

polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.2" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.2" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.2" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.2" }

service = { package = "moonbeam-service", path = "../service", default-features = false }
cli-opt = { package = "moonbeam-cli-opt", path = "../cli-opt", default-features = false }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }

[features]
default = [ "wasmtime" ]
wasmtime = [ "sc-cli/wasmtime" ]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
